[role_backend]
10.0.10.124 ansible_user=ec2-user ansible_ssh_private_key_file=./keys/terraform-ansible-webapp-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ./keys/terraform-ansible-webapp-key.pem ec2-user@3.254.75.195"'

[role_frontend]
3.254.75.195 ansible_user=ec2-user ansible_ssh_private_key_file=./keys/terraform-ansible-webapp-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
